# Generated by Django 6.0.1 on 2026-02-04 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_company_shipment_company_profile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name_plural': 'Companies'},
        ),
        migrations.AlterField(
            model_name='company',
            name='registration_number',
            field=models.CharField(default=None, editable=False, max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
